modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="initialinventory" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Initial Inventory" #mandatory
credits="" #optional
authors="Jaredlll08" #optional
updateJSONURL="https://updates.blamejared.com/get?n=AmbientEnvironment&gv=1.16.1"
description='''
Lets you define starting items through zenscript
'''