license = "MIT"
modLoader = "javafml"
loaderVersion = "[34,)"
[[mods]]
modId = "initialinventory"
version = "${file.jarVersion}"
displayName = "Initial Inventory"
authors = "Jaredlll08"
updateJSONURL = "https://updates.blamejared.com/get?n=InitialInventory&gv=1.16.5"
description = '''
Lets you define starting items through zenscript
'''